import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TrackContextProvider } from "@/lib/track.wrapper";
import { UserContextProvider } from "@/lib/user.wrapper";
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import { Toaster } from "@/components/ui/sonner"
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const DRAWER_WIDTH = 240;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const dns = require('dns');
    dns.setDefaultResultOrder('ipv4first');
    return (
        <html lang="en">
            <body className="bg-black">
                <NextAuthWrapper>
                    <TrackContextProvider>
                        <UserContextProvider>
                            {children}
                            <Toaster />
                        </UserContextProvider>
                    </TrackContextProvider>
                </NextAuthWrapper>
            </body>
        </html>
    );
}
